"""penyesuaian interaksi

Revision ID: a009eb840fab
Revises: 
Create Date: 2026-02-05 10:44:41.530320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a009eb840fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipe', sa.String(length=20), nullable=True),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_is_active'))
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('categories')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('date'))
        batch_op.drop_index(batch_op.f('idx_date'))

    op.drop_table('analytics')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_awal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_perbaikan', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alamat_manual', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status_warna', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('urgency_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_is_public'))
        batch_op.drop_index(batch_op.f('idx_kategori'))
        batch_op.drop_index(batch_op.f('idx_public_status'))
        batch_op.drop_index(batch_op.f('idx_sentiment'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_index(batch_op.f('idx_user_status'))
        batch_op.drop_constraint(batch_op.f('reports_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('views_count')
        batch_op.drop_column('hashtag')
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('foto')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('status')
        batch_op.drop_column('bukti_perbaikan')
        batch_op.drop_column('sentiment')
        batch_op.drop_column('catatan_admin')
        batch_op.drop_column('alamat_lokasi')
        batch_op.drop_column('is_incognito')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_wa', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('kecamatan', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('poin_warga', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('nik',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='NIK 16 digit mulai 3517',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='user | admin',
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_nik'))
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.create_unique_constraint(None, ['no_wa'])
        batch_op.drop_column('alamat')
        batch_op.drop_column('last_login')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('telepon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telepon', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('last_login', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('alamat', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_nik'), ['nik'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               comment='user | admin',
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nik',
               existing_type=mysql.VARCHAR(length=16),
               comment='NIK 16 digit mulai 3517',
               existing_nullable=False)
        batch_op.drop_column('is_verified')
        batch_op.drop_column('poin_warga')
        batch_op.drop_column('kecamatan')
        batch_op.drop_column('no_wa')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_incognito', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alamat_lokasi', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('catatan_admin', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sentiment', mysql.VARCHAR(length=20), nullable=True, comment='positive | neutral | negative'))
        batch_op.add_column(sa.Column('bukti_perbaikan', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True, comment='pending | approved | proses | selesai | rejected'))
        batch_op.add_column(sa.Column('resolved_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('foto', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('approved_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('sentiment_score', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hashtag', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('views_count', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('idx_public_status'), ['is_public', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_kategori'), ['kategori'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('is_approved')
        batch_op.drop_column('urgency_level')
        batch_op.drop_column('status_warna')
        batch_op.drop_column('alamat_manual')
        batch_op.drop_column('foto_perbaikan')
        batch_op.drop_column('foto_awal')

    op.create_table('analytics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('pending_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('approved_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('proses_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('selesai_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rejected_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_users', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('active_users', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_interactions', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('date'), ['date'], unique=True)

    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=50), server_default=sa.text("'bi-chat-dots'"), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_active'), ['is_active'], unique=False)

    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('report_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False, comment='status_update | comment | support'),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('notifications_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_read'), ['user_id', 'is_read'], unique=False)

    op.drop_table('interactions')
    # ### end Alembic commands ###
