"""tambah kolom category_id ke reports

Revision ID: b0b7dde5a068
Revises: a009eb840fab
Create Date: 2026-02-11 14:05:51.433751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0b7dde5a068'
down_revision = 'a009eb840fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('date'))
        batch_op.drop_index(batch_op.f('idx_date'))

    op.drop_table('analytics')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_is_active'))
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.alter_column('level_bahaya',
               existing_type=mysql.ENUM('waspada', 'siaga', 'bahaya'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'bahaya'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('kategori',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('sentiment',
               existing_type=mysql.ENUM('positive', 'neutral', 'negative', 'marah', 'panik'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'neutral'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('approved_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('resolved_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_is_public'))
        batch_op.drop_index(batch_op.f('idx_kategori'))
        batch_op.drop_index(batch_op.f('idx_public_status'))
        batch_op.drop_index(batch_op.f('idx_sentiment'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_index(batch_op.f('idx_user_status'))
        batch_op.drop_constraint(batch_op.f('fk_report_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reports_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('foto_3')
        batch_op.drop_column('foto_2')
        batch_op.drop_column('target_selesai')
        batch_op.drop_column('petugas_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='NIK 16 digit mulai 3517',
               existing_nullable=False)
        batch_op.alter_column('no_wa',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('kecamatan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_nik'))
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('telepon')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('telepon', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_nik'), ['nik'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('kecamatan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('no_wa',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('nik',
               existing_type=mysql.VARCHAR(length=16),
               comment='NIK 16 digit mulai 3517',
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petugas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_selesai', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('foto_2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_3', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_report_category'), 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_user_status'), ['user_id', 'status_warna'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status_warna'], unique=False)
        batch_op.create_index(batch_op.f('idx_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('idx_public_status'), ['is_public', 'status_warna'], unique=False)
        batch_op.create_index(batch_op.f('idx_kategori'), ['kategori'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('resolved_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('sentiment',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('positive', 'neutral', 'negative', 'marah', 'panik'),
               existing_nullable=True,
               existing_server_default=sa.text("'neutral'"))
        batch_op.alter_column('kategori',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('level_bahaya',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('waspada', 'siaga', 'bahaya'),
               existing_nullable=True,
               existing_server_default=sa.text("'bahaya'"))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('report_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False, comment='status_update | comment | support'),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('notifications_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_read'), ['user_id', 'is_read'], unique=False)

    op.create_table('analytics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('pending_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('approved_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('proses_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('selesai_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rejected_reports', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_users', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('active_users', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_interactions', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('date'), ['date'], unique=True)

    # ### end Alembic commands ###
